(car '((peas carrots tomatoes) (pork beef chicken)))
(cdr '(peas carrots tomatoes))
(cdr (car '((peas carrots tomatoes) (pork beef chicken))))
(cdar '((peas carrots tomatoes) (pork beef chicken)))
(cddr '((peas carrots tomatoes) (pork beef chicken) duck))
(caddr '((peas carrots tomatoes) (pork beef chicken) duck))
(cddar '((peas carrots tomatoes) (pork beef chicken) duck))
(cadadr '((peas carrots tomatoes) (pork beef chicken) duck))